In [1]:
import numpy as np

from minitorch.autodiff import Tensor, TensorData, topological_sort, tensor
from minitorch.functional import product
import minitorch.autodiff.tensor_functions as tf
from minitorch.autodiff.tensor_functions import grad_central_difference, grad_check

from minitorch.testing import MathTestOperators, MathTestVariable

### Tensors

In [2]:
# Create tensor
input_dim, output_dim = 2, 3

weights = tf.rand(shape=(input_dim, output_dim))
bias = tf.rand(shape=(output_dim,))

In [3]:
def forward(inputs):
    _inputs = inputs.view(*inputs.shape, 1)
    _weights = weights.view(1, *weights.shape)

    # Collapse dimension
    _out = (_inputs * _weights).sum(dim=1)
    _out = _out.view(inputs.shape[0], output_dim)
    return _out + bias

In [4]:
inputs = tf.rand(shape=(5, 2))
outputs = forward(inputs)
outputs


[
	[1.36 0.92 1.09]
	[1.42 0.99 1.11]
	[1.31 0.87 1.07]
	[1.38 0.95 1.09]
	[1.29 0.83 1.09]
]

In [5]:
# Check same as numpy
inputs_np = inputs.data.storage.reshape(inputs.shape)
weights_np = weights.data.storage.reshape(weights.shape)
bias_np = bias.data.storage.reshape(bias.shape)
outputs_np = np.dot(inputs_np, weights_np) + bias

In [11]:
# Output shape should be (5, 3)
inputs


[
	[0.35 0.21]
	[0.38 0.26]
	[0.30 0.21]
	[0.42 0.16]
	[0.12 0.38]
]

In [10]:
inputs_np

array([[0.35275794, 0.21469372],
       [0.37978948, 0.26297949],
       [0.29836192, 0.21136386],
       [0.41890818, 0.16407718],
       [0.11891459, 0.38141199]])