In [1]:
import numpy as np

from minitorch.autodiff import Tensor, TensorData
from minitorch.functional import product

### Tensors

In [2]:
# Creation
shape = (5, )
data = np.ones(shape).flatten()
td = TensorData(data, shape=shape)
t = Tensor(data=td)


In [3]:
scalar = 3.0
result = Inv.apply(t)
result


[1.00 1.00 1.00 1.00 1.00]

In [4]:
3 / t

other = 
[3.00]
inv = 
[1.00 1.00 1.00 1.00 1.00]



[3.00 3.00 3.00 3.00 3.00]

In [5]:
t / 3

in true div.



[0.33 0.33 0.33 0.33 0.33]

In [ ]:
tuple(np.array([[1, 2, 3]]))